name: Code Quality Checks and Test Trigger

on:
  pull_request:
    branches: [dev]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: |
          flake8 .

  merge-to-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch Branches
        run: |
          git fetch origin

      - name: Checkout Target Branch
        run: |
          git checkout test || git checkout -b test origin/dev

      - name: Approval Check
        run: |
          sender_login=$(jq -r ".sender.login" $GITHUB_EVENT_PATH)
          if [ "$sender_login" != "revolutionaryanusha" ]; then
            echo "Error: Only the admin user can initiate this PR."
            exit 1
          fi

      - name: Merge Changes
        run: |
          git merge origin/${GITHUB_HEAD_REF} --no-edit
          git push origin test
